  metadata:
    uid: production
    apiVersion: v1
    type: Namespace
  spec:
    acl:
      allowHostNetworking: false
      allowPrivilegedContainers: false
      allowedHosts: []
      allowedProjects:
      - uid: sales
      - uid: account
      - uid: corp-ui
      - uid: client-mgmt
      - uid: analytics
      allowedUsers: []
      deniedLabels: []
      deniedProjects: []
      deniedUsers: []
      enabled: true
    enabled: true
    quotas:
      enabled: true
      items:
      - description: ""
        name: maxpods
        rules:
        - limits:
          - kind: pods
            value: "0"
          targets:
          - aggregate: true
            entities:
            - kind: Project
              uid: sales
            - kind: Project
              uid: account
            - kind: Project
              uid: client-mgmt
            - kind: Project
              uid: corp-ui


